---
title: "Evaluating Content Alignment in Computerized Adaptive Testing"
author: "Wise, S. L., et al. (2015)"
output:
  xaringan::moon_reader:
    css: ["default", "../svm-xaringan-style.css"]
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
knitr::opts_chunk$set(dev = 'svg')
options(device = function(file, width, height) {
  svg(tempfile(), width = width, height = height)
})
library(tidyverse)
library(stevemisc)
```



class: center, middle
# 
## Goal

.center[** Highlights  the process of evaluating content alignment in adaptive test.**] 
---
# Content Alignment
##  Fixed Form and CAT
Degree of agreement between the standards and the test content

--
## CAT
Appropriate level of challenge for test taker
---

# Traditional Aliggnment Process

--
- Use of explicit
criteria and report on how these criteria are acceptably or unacceptably met for specific standards and a particular
test form (Rothman, Slattery, Vranek, & Resnick, 2002;Webb, 1997)

<br>
<br>


--
- Use of alignment index
that represents the degree of the overall alignment for the
test form with the full set of standards (Polikoff, Porter, &
Smithson, 2011; Porter, 2002)

<br>
<br>

--
 .center[**Evaluators examine and review items on a test form**]
---

# Challenges of Traditional Alignment Process

--
- No common test form to evaluate

<br>

--
- Reviewing item pool is impractical

<br>

--
- Test event and item pool may no be comparable
---

# Testing Algorith and Content Alignment

The item selection algorithm choose items of appropriate difficulty while satisfying content constraints.

---

# Alignment information

### The Item Pool
The successful implementation of any CAT is largely dependent on the adequacy of its item pool.

<br>
--
**Meta-tags**

- Tags of sample items are evaluated for accuracy to avoid mismatch between meta-tag and content attributes.  

<br>

--
**Size and Content Distribution**   

- The distribution of item difficulty values is adequate for
assessing examinees across a specified range of achievement
levels.  

-  The number of items is sufficient to satisfy any
requirements for both score precision and managing item exposure. 

---

# Alignment information

### The Item Selection Algorithm
The item selection algorithm is crucial to a CAT’s implementation of the test plan.

<br>
--
**Challenge**

- Algorithm may be written in code that is challenging to interpret.
- Algorithm may be viewed by the test developer as intellectual property that is proprietary

<br>

--
**Work Around**   

The evaluator
may need to use the documentation of the algorithm rather
than the algorithm itself to understand the processes used to
control content for the test
---
